### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by YeldhamDev** [flathub/org.develz.Crawl#10] opened 2020-09-19 02:43 UTC
The game crashes with the following message: `ASSERT(_parent) in 'database.cc' at line 251 failed.`

**Comment by arteymix** [comment] 2020-09-19 22:34
Do you know which version of Crawl you're running?

**Comment by YeldhamDev** [comment] 2020-09-19 22:48
The latest from Flathub: 0.25.1

**Comment by arteymix** [comment] 2020-09-20 01:52
What about Flatpak version or Linux distro?

I had this exact issue with my previous OS release and I never really managed to isolate the problem.

**Comment by YeldhamDev** [comment] 2020-09-20 02:13
Version 1.8.1 on Manjaro.

**Comment by rawlins** [comment] 2021-12-07 20:59
Does flatpak set mtime to 0 for all files or something similar? (Some reproducible build or packaging systems might do this, and googling found related issues on other flathub repositories.) The dcss db code assumes real mtimes to know when to regenerate the dbs from the raw data files at run time, and this crash could happen if every db source file has a 0 mtime. I've made a commit to dcss to hopefully handle this situation more gracefully (https://github.com/crawl/crawl/commit/9c4cb8273db1343db25ed291406670c9f124c678).

However, if this is indeed the issue, as noted in that commit message, packagers changing mtimes for *runetime game data* files is not recommended or supported by us. (It's fine for any non-data files of course or anything that happens at build time, e.g. source files, tiles, species data etc.)

**Comment by arteymix** [comment] 2021-12-07 21:16
@YeldhamDev Would you mind running `stat` on some of the files located under `/app/share/crawl/dat/database`? You can open a shell inside the Flatpak using:

```bash
flatpak run --command=bash org.develz.Crawl
```

On my machine, the files appear to have correct mtime values:

```
  File: /app/share/crawl/dat/database/FAQ.txt
  Size: 15107     	Blocks: 32         IO Block: 4096   regular file
Device: 23h/35d	Inode: 798197      Links: 2
Access: (0644/-rw-r--r--)  Uid: (65534/nfsnobody)   Gid: (65534/nfsnobody)
Access: 2021-08-01 10:08:24.673698249 -0700
Modify: 2021-08-01 10:08:24.373694954 -0700
Change: 2021-09-21 00:09:42.797946162 -0700
 Birth: 2021-08-01 10:08:24.373694954 -0700
```

**Comment by rawlins** [comment] 2021-12-07 21:44
Well, that all looks fine.

For reference, here are some of the issues I ran across that made me think this might be the issue, or at least have been at one point:
* https://github.com/flatpak/flatpak/issues/926
* https://github.com/flatpak/flatpak/issues/799

**Comment by arteymix** [comment] 2021-12-07 23:25
I'll close this since it seems to be fixed in Flatpak somehow and eventually will get fixed upstream. If anyone experiences this issue again, please feel free to reopen.

**Closed by arteymix** 2021-12-07 23:25 UTC
Labels: bug
