### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.develz.Crawl#3] opened 2018-04-23 22:38 UTC
ASSERT(_parent) in 'database.cc' at line 268 failed.

ASSERT(_parent) in 'database.cc' at line 268 failed.

We crashed! This is likely due to a bug in Crawl. 
Please submit a bug report at https://crawl.develz.org/mantis/ and include:
- The crash report: /sysroot/home/leandro/.crawl/morgue/crash--20180423-193531.txt
- Your save file: /sysroot/home/leandro/.crawl/saves/.cs
- A description of what you were doing when this crash occurred.

**Comment by arteymix** [comment] 2018-04-24 04:50
You should report this to Crawl devs. I'll close this, but if you have any evidence that this is due to the Flatpak, I'll investigate further.

**Comment by LeandroStanger** [comment] 2018-04-25 01:35
@ramcq Could help

**Comment by barthalion** [comment] 2018-04-25 08:27
@arteymix: Same happens for me. Did it even worked in the first place when it got merged? It's bad user experience to display applications in the store that fail to start like this.

**Comment by barthalion** [comment] 2018-04-25 08:29
https://github.com/flathub/org.develz.Crawl/blob/master/org.develz.Crawl.json#L13 Also here it should be `--persist=.crawl` instead.

**Comment by barthalion** [comment] 2018-04-25 16:49
Also I can confirm that Crawl from Arch Linux repository starts correctly, while flatpak doesn't.

**Comment by icarito** [comment] 2018-08-22 07:09
Works for me!

**Comment by LeandroStanger** [comment] 2018-09-18 21:43
Does not open
```
ASSERT(_parent) in 'database.cc' at line 252 failed.

ASSERT(_parent) in 'database.cc' at line 252 failed.

We crashed! This is likely due to a bug in Crawl. 
Please submit a bug report at https://crawl.develz.org/mantis/ and include:
- The crash report: /sysroot/home/leandro/.crawl/morgue/crash--20180918-184329.txt
- Your save file: /sysroot/home/leandro/.crawl/saves/.cs
- A description of what you were doing when this crash occurred.

```

**Comment by arteymix** [comment] 2018-09-19 16:27
I've tried to debug this a couple of time. I think that someone from the Crawl dev team should take a look.

**Comment by alexpattyn** [comment] 2020-03-23 05:21
Still seems to be a issue. 

```
[apattyn@$MACHINE Downloads]$ flatpak run org.develz.Crawl 
ASSERT(_parent) in 'database.cc' at line 252 failed.

ASSERT(_parent) in 'database.cc' at line 252 failed.

We crashed! This is likely due to a bug in Crawl. 
Please submit a bug report at https://crawl.develz.org/mantis/ and include:
- The crash report: /var/home/apattyn/.crawl/morgue/crash--20200323-011212.txt
- Your save file: /var/home/apattyn/.crawl/saves/.cs
- A description of what you were doing when this crash occurred.
```

Just ran `flatpak run org.develz.Crawl `

[crash--20200323-011212.txt](https://github.com/flathub/org.develz.Crawl/files/4367329/crash--20200323-011212.txt)

**Comment by arteymix** [comment] 2020-03-23 05:25
@alexpattyn Could you try renaming `~/.crawl` and rerun the flatpak?

**Comment by alexpattyn** [comment] 2020-03-23 05:57
Sure, I just delete it since it was a fresh install. But same issue. 

```
$ flatpak run org.develz.Crawl 
ASSERT(_parent) in 'database.cc' at line 252 failed.

ASSERT(_parent) in 'database.cc' at line 252 failed.

We crashed! This is likely due to a bug in Crawl. 
Please submit a bug report at https://crawl.develz.org/mantis/ and include:
- The crash report: /var/home/apattyn/.crawl/morgue/crash--20200323-015526.txt
- Your save file: /var/home/apattyn/.crawl/saves/.cs
- A description of what you were doing when this crash occurred.
```

[crash--20200323-015526.txt](https://github.com/flathub/org.develz.Crawl/files/4367451/crash--20200323-015526.txt)

**Comment by alexpattyn** [comment] 2020-03-23 06:02
I am currently running Fedora 32 beta, specifically: 

```
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200319.n.0 (2020-03-19T08:25:20Z)
                BaseCommit: c1eee0a18bef026b066d04392773550141e2121329ee75da88f190b2b622fb53
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: gnome-tweak-tool
```

Although this issue is on F31.

**Comment by arteymix** [comment] 2020-03-23 16:28
I experienced this bug in the past, but since I'm on Fedora 32 beta, it does not happen anymore.

It would be nice to have more details on the crash. You can debug inside the Flatpak by layering the SDK.

```
flatpak install org.freedesktop.Sdk
flatpak run --devel --command=bash org.develz.Crawl
gdb crawl
gdb> run
# crash
gdb> gcore <file>
gdb> backtrace
```

The other useful trick is `strace` to record the system calls. There might be issues opening some files.

**Comment by arteymix** [comment] 2020-03-23 16:29
If you send me the coredump, the backtrace and strace output, I can investigate a bit and report the bug to the Crawl team.

**Comment by alexpattyn** [comment] 2020-03-26 21:00
It seems that will the latest update from flathub it works. So the issue can be closed since I can't reproduce it. If I encounter this bug in the future I'll run those commands and post them here.

**Comment by LeandroStanger** [comment] 2020-03-26 21:56
[crash--20200326-185457.txt](https://github.com/flathub/org.develz.Crawl/files/4390198/crash--20200326-185457.txt)

**Comment by arteymix** [comment] 2020-08-04 17:18
Everything has been working reliably since I updated the platform to freedesktop 19.08. If the problem resurfaces, feel free to reopen this issue.

**Closed by arteymix** 2020-08-04 17:18 UTC
Labels: bug
