### ISSUE TITLE
Letter key input does not work on wayland. 

### ISSUE THREAD

**Issue by dwestford17** [flathub/org.develz.Crawl#15] opened 2022-04-21 12:46 UTC
When on wayland, the letter keys on the keyboard do not work. I can move with the arrow keys but all other actions tied to the letter keys on the keyboard do not work. When switched to an xorg session, there are no issues. No issues with mouse input on either.

OS: Fedora 36 (issue also present on Fedora 35)
DE: Gnome Wayland Session

**Comment by arteymix** [comment] 2022-04-21 15:55
Input is handled by SDL. Is this occurring in other flatpaked games based on SDL?

**Comment by dwestford17** [comment] 2022-04-21 16:04
The flatpak version of Brogue CE has the same issue.

**Comment by 1player** [comment] 2022-08-25 10:02
Can't reproduce on Fedora Silverblue 36, GNOME on Wayland.

**Comment by arteymix** [comment] 2022-08-25 16:19
It's unclear if this is reproducible, so I'll close this.

**Closed** 2022-08-25 16:19 UTC
